spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aoce
    username: role_for_spring
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
#  web:
#    resources:
#      cache:
#        period: 0